PLATFORM="macos"
ROLES="base server headless"

HOST_STOW=""
HOST_PACKAGE_GROUPS_MACOS="cloud"
HOST_DEFAULT_GROUPS_MACOS=""
HOST_APP_GROUPS_MACOS=""
HOST_HOTKEY_GROUPS_MACOS=""
HOST_SCRIPT_GROUPS_MACOS=""
