#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# (No scripting as it needs to have the privileges to run the command)
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist on

yabai -m config window_shadow on
yabai -m config window_opacity off

yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50

yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 0
yabai -m config layout bsp

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

yabai -m rule --add app="^System Settings$" manage=off

echo "yabai configuration loaded."

